### ISSUE TITLE
Command Execution Failed (Discord slash commands)

### ISSUE THREAD

**Issue by djdoolky76** [torikushiii/hoyolab-auto#25]
I'm getting command execution failed when I'm trying to execute `/note` command in Discord; however, the script keeps running, and I have the same error on the bot reply as well

![image](https://github.com/torikushiii/hoyolab-auto/assets/30578879/99ee138d-26a5-46cd-8933-40dde38d38d6)

Logs:
```css
  message: 'Command execution failed',
  data: {
    command: 'notes',
    invocation: 'notes',
    platform: 1,
    args: [ 'starrail' ],
    error: Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
        at ChatInputCommandInteraction.reply (/root/hoyolab-auto/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:104:46)
        at Command.notes [as code] (/root/hoyolab-auto/commands/notes/index.js:188:23)
        at async Command.checkAndRun (/root/hoyolab-auto/classes/command.js:202:16)
        at async DiscordController.handleCommand (/root/hoyolab-auto/platforms/discord.js:182:21)
        at async Client.<anonymous> (/root/hoyolab-auto/platforms/discord.js:109:4) {
      code: 'InteractionAlreadyReplied'
    }
  }
}
```
